/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example.quickfix.client;

import java.io.FileInputStream;
import java.time.LocalDateTime;
import java.util.Scanner;

import quickfix.DefaultSessionFactory;
import quickfix.FileLogFactory;
import quickfix.FileStoreFactory;
import quickfix.Initiator;
import quickfix.LogFactory;
import quickfix.Message;
import quickfix.MessageStoreFactory;
import quickfix.SessionFactory;
import quickfix.SessionSettings;
import quickfix.SocketInitiator;
import quickfix.field.*;

public class App {

    private static Scanner keyboard = new Scanner(System.in);

    private static String prompt(String msg) {
        return prompt(msg, "string");
    }


    private static String prompt(String msg, String type) {
        System.out.printf("%s [%s] >>> ", msg, type);
        return keyboard.nextLine();
    }

    private static char promptChar(String msg) {
        String s = prompt(msg, "char");
        return s.charAt(0);
    }

    public static void main(String[] args) {
        // FooApplication is your class that implements the Application interface
        // https://www.quickfixj.org/usermanual/2.3.0/usage/application.html
        MyApplication application = new MyApplication();

        try {
            String configFilename = System.getProperty("user.dir") + "/config";
            System.out.println(configFilename);
            SessionSettings settings = new SessionSettings(new FileInputStream(configFilename));

            LogFactory logFactory = new FileLogFactory(settings);

            MessageStoreFactory messageFactory = new FileStoreFactory(settings);

            SessionFactory sessionFactory= new DefaultSessionFactory(application, messageFactory, logFactory);

            Initiator initiator = new SocketInitiator(sessionFactory, settings, 1000000);

            initiator.start();

            while(true) {
                String command = prompt("Command", "print, place, cancel, replace");

                Message message = new Message();

                try {
                    switch (command) {
                        case "print" -> {
                           System.out.print(application.drainMessagesAsPrettyString());
                         }

                        case "place" -> {
                             quickfix.fix42.NewOrderSingle nos = new quickfix.fix42.NewOrderSingle();

                             nos.set(new ClOrdID(prompt("ClOrdID")));
                             nos.set(new Symbol(prompt("Symbol")));
                             nos.set(new Side(promptChar("Side (1=Buy,2=Sell,5=SellShort,9=BuyToCover)")));
                             nos.set(new TransactTime(LocalDateTime.now()));
                             nos.set(new OrdType(promptChar("OrdType (1=Market,2=Limit,3=Stop,4=StopLimit)")));
                             nos.set(new ExDestination(prompt("ExDestination (e.g. INET, XNYS, ARCA)")));
                             nos.set(new OrderQty(Double.parseDouble(prompt("OrderQty"))));

                             // Optional: Price only if limit or stop-limit
                             char ordType = nos.getOrdType().getValue();
                             if (ordType == OrdType.LIMIT || ordType == OrdType.STOP_LIMIT) {
                                  nos.set(new Price(Double.parseDouble(prompt("Price"))));
                             }

                       message = nos;
                    }

                        case "cancel" -> {
                             quickfix.fix42.OrderCancelRequest cancel = new quickfix.fix42.OrderCancelRequest();

                              // Required per Lime spec
                             cancel.set(new quickfix.field.ClOrdID(prompt("ClOrdID (new cancel id)")));   // 11
                             String orderId = prompt("OrderID [37] (optional; Enter to skip)");           // 37
                             if (!orderId.isEmpty()) {
                             cancel.set(new quickfix.field.OrderID(orderId));                         // 37 present => 41 ignored by Lime
                             } else {
                              cancel.set(new quickfix.field.OrigClOrdID(prompt("OrigClOrdID")));       // 41
                             }

                              // If you ever need “cancel all open”:
                              // cancel.set(new quickfix.BooleanField(9020, true)); // 9020 CancelAllOpen (optional)

                              message = cancel;
                       }

                        case "replace" -> {
                            quickfix.fix42.OrderCancelReplaceRequest replace = new quickfix.fix42.OrderCancelReplaceRequest();

                            // Required per Lime spec
                            replace.set(new quickfix.field.ClOrdID(prompt("ClOrdID (new replace id)")));  // 11
                            replace.set(new quickfix.field.OrigClOrdID(prompt("OrigClOrdID")));           // 41

                            // Optional but typical fields for a replace
                            String orderId = prompt("OrderID [37] (optional; Enter to skip)");
                            if (!orderId.isEmpty()) {
                            replace.set(new quickfix.field.OrderID(orderId));
                            }

                            replace.set(new quickfix.field.Symbol(prompt("Symbol")));                    // 55
                            replace.set(new quickfix.field.Side(promptChar("Side (1=Buy,2=Sell,5=SS,9=BTC)"))); // 54
                            replace.set(new quickfix.field.TransactTime(LocalDateTime.now()));           // 60

                            String qty = prompt("OrderQty [38] (optional; Enter to skip)");
                            if (!qty.isEmpty()) {
                                replace.set(new quickfix.field.OrderQty(Double.parseDouble(qty)));
                            }

                            String px = prompt("Price [44] (optional; Enter to skip)");
                            if (!px.isEmpty()) {
                                 replace.set(new quickfix.field.Price(Double.parseDouble(px)));
                            }

                            message = replace;
                         }

						default -> {
                            System.out.println("Command not found");
                            continue;
                        }
                    }
                } catch(Exception e) {
                    e.printStackTrace();
                    System.exit(1);
                }

                application.sendMessage(message);
            }
        } catch (Exception e) {
            // System.out.println("Config error");
            e.printStackTrace();
        }
        System.out.println("Exit");
        System.exit(2);
    }
}
